/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface CATEGORIAEntity {
  'Descripcion'?: string | null;
  'Estado'?: boolean | null;
  'IdCategoria'?: number;
}
export interface ClienteEntity {
  'Apellido': string;
  'DNI': number;
  'IdCliente'?: number;
  'Nombre': string;
}
export interface COMPRAEntity {
  'FechaRegistro'?: Date | null;
  'IdCompra'?: number;
  'IdProveedor'?: number | null;
  'IdUsuario'?: number | null;
  'MontoTotal'?: number | null;
}
export interface DETALLE_COMPRAEntity {
  'Cantidad'?: number | null;
  'FechaRegistro'?: Date | null;
  'IdCompra'?: number | null;
  'IdDetalleCompra'?: number;
  'IdProducto'?: number | null;
  'MontoTotal'?: number | null;
  'PrecioCompra'?: number | null;
  'PrecioVenta'?: number | null;
}
export interface DETALLE_VENTAEntity {
  'Cantidad'?: number | null;
  'FechaRegistro'?: Date | null;
  'IdDetalleVenta'?: number;
  'IdProducto'?: number | null;
  'IdVenta'?: number | null;
  'PrecioVenta'?: number | null;
  'Subtotal'?: number | null;
}
export interface PERMISOEntity {
  'IdPermiso'?: number;
  'IdRol'?: number | null;
  'NombreMenu'?: string | null;
}
export interface PRODUCTOEntity {
  'codigoProducto'?: string | null;
  'Descripcion'?: string | null;
  'Estado'?: boolean | null;
  'FechaRegistro'?: Date | null;
  'IdCategoria'?: number | null;
  'IdProducto'?: number;
  'Nombre'?: string | null;
  'PrecioCompra'?: number | null;
  'PrecioVenta'?: number | null;
  'Stock'?: number;
}
export interface PROVEEDOREntity {
  'Documento'?: string | null;
  'Estado'?: boolean | null;
  'IdProveedor'?: number;
  'Nombre'?: string | null;
  'Telefono'?: string | null;
}
export interface ROLEntity {
  'Descripcion'?: string | null;
  'IdRol'?: number;
}
export interface USUARIOEntity {
  'Apellido'?: string | null;
  'Clave'?: string | null;
  'Direccion'?: string | null;
  'DNI'?: string | null;
  'Email'?: string | null;
  'Estado'?: boolean | null;
  'FechaNacimiento'?: Date | null;
  'IdRol'?: number | null;
  'IdUsuario'?: number;
  'Nombre'?: string | null;
  'Telefono'?: string | null;
}
export interface VentaEntity {
  'FechaRegistro'?: Date | null;
  'IdCliente': number;
  'IdUsuario'?: number | null;
  'IdVenta'?: number;
  'MontoCambio'?: number | null;
  'MontoPago'?: number | null;
  'MontoTotal'?: number | null;
}
