/*
 * This code was auto-generated by generator-mssql-types.
 * See https://github.com/jweyrich/generator-mssql-types for more information.
 * WARNING: If you change anything in this file it may be automatically overwriten!
 */

//import { Datasource, IProcedureResult, Procedure, SqlTypes } from '@internal/mssql-connector';
import { database } from '../../config/database';
import sql from 'mssql';

//export class SP_AGREGARDETALLECOMPRA {
   // readonly _repository: Datasource;

    //constructor(repository: Datasource) {
    //    this._repository = repository;
    //}

 export const execute = async(params: Params): Promise<sql.IProcedureResult<Result>> => {
       
    // const procedure = new Procedure<Result>('SP_AGREGARDETALLECOMPRA');
    var request = new sql.Request(database);
        if (params.IdCompra != null) {
            request.input('IdCompra', sql.Int(), params.IdCompra);
            // procedure.addParameter('IdCompra', params.IdCompra, SqlTypes.Int());
        }
        if (params.IdProducto != null) {
            request.input('IdProducto', sql.Int(), params.IdProducto);
            // procedure.addParameter('IdProducto', params.IdProducto, SqlTypes.Int());
        }
        if (params.PrecioCompra != null) {
            request.input('PrecioCompra', sql.Decimal(18, 2), params.PrecioCompra);
            // procedure.addParameter('PrecioCompra', params.PrecioCompra, SqlTypes.Decimal(18, 2));
        }
        if (params.PrecioVenta != null) {
            request.input('PrecioVenta', sql.Decimal(18, 2), params.PrecioVenta);
            // procedure.addParameter('PrecioVenta', params.PrecioVenta, SqlTypes.Decimal(18, 2));
        }
        if (params.Cantidad != null) {
            request.input('Cantidad', sql.Int(), params.Cantidad);
            // procedure.addParameter('Cantidad', params.Cantidad, SqlTypes.Int());
        }
        if (params.MontoTotal != null) {
            request.input('MontoTotal', sql.Decimal(18, 2), params.MontoTotal);
            // procedure.addParameter('MontoTotal', params.MontoTotal, SqlTypes.Decimal(18, 2));
        }
        if (params.FechaRegistro != null) {
            request.input('FechaRegistro', sql.DateTime(), params.FechaRegistro);
            // procedure.addParameter('FechaRegistro', params.FechaRegistro, SqlTypes.DateTime());
        }
    //request.output('output_parameter', sql.VarChar(50));
    const recordsets = await request.execute<Result>('SP_AGREGARDETALLECOMPRA');
    console.log("RecordSet SP_AGREGARDETALLECOMPRA",recordsets)
    return recordsets
    //return await this._repository.execProcedure(procedure);

    }
//}

/*
 * All attributes below are optional because MSSQL does not give us the correct information.
 * We'd need to write a custom T-SQL parser to get this piece of information.
 */
export type Params = {
    IdCompra?: number; /* int */
    IdProducto?: number; /* int */
    PrecioCompra?: number; /* decimal(18, 2) */
    PrecioVenta?: number; /* decimal(18, 2) */
    Cantidad?: number; /* int */
    MontoTotal?: number; /* decimal(18, 2) */
    FechaRegistro?: Date; /* datetime */
};

export type Result = void;
