/*
 * This code was auto-generated by generator-mssql-types.
 * See https://github.com/jweyrich/generator-mssql-types for more information.
 * WARNING: If you change anything in this file it may be automatically overwriten!
 */

//import { Datasource, IProcedureResult, Procedure, SqlTypes } from '@internal/mssql-connector';
import { database } from '../../config/database';
import sql from 'mssql';

//export class SP_AGREGARCOMPRA {
   // readonly _repository: Datasource;

    //constructor(repository: Datasource) {
    //    this._repository = repository;
    //}

 export const execute = async(params: Params): Promise<sql.IProcedureResult<Result>> => {
       
    // const procedure = new Procedure<Result>('SP_AGREGARCOMPRA');
    var request = new sql.Request(database);
        if (params.IdUsuario != null) {
            request.input('IdUsuario', sql.Int(), params.IdUsuario);
            // procedure.addParameter('IdUsuario', params.IdUsuario, SqlTypes.Int());
        }
        if (params.IdProveedor != null) {
            request.input('IdProveedor', sql.Int(), params.IdProveedor);
            // procedure.addParameter('IdProveedor', params.IdProveedor, SqlTypes.Int());
        }
        if (params.MontoTotal != null) {
            request.input('MontoTotal', sql.Decimal(18, 0), params.MontoTotal);
            // procedure.addParameter('MontoTotal', params.MontoTotal, SqlTypes.Decimal(18, 0));
        }
        if (params.FechaRegistro != null) {
            request.input('FechaRegistro', sql.DateTime(), params.FechaRegistro);
            // procedure.addParameter('FechaRegistro', params.FechaRegistro, SqlTypes.DateTime());
        }
    //request.output('output_parameter', sql.VarChar(50));
    const recordsets = await request.execute<Result>('SP_AGREGARCOMPRA');
    console.log("RecordSet SP_AGREGARCOMPRA",recordsets)
    return recordsets
    //return await this._repository.execProcedure(procedure);

    }
//}

/*
 * All attributes below are optional because MSSQL does not give us the correct information.
 * We'd need to write a custom T-SQL parser to get this piece of information.
 */
export type Params = {
    IdUsuario?: number; /* int */
    IdProveedor?: number; /* int */
    MontoTotal?: number; /* decimal(18, 0) */
    FechaRegistro?: Date; /* datetime */
};

export type Result = {
    Success: number; /* int */
} | null;
