/*
 * This code was auto-generated by generator-mssql-types.
 * See https://github.com/jweyrich/generator-mssql-types for more information.
 * WARNING: If you change anything in this file it may be automatically overwriten!
 */

//import { Datasource, IProcedureResult, Procedure, SqlTypes } from '@internal/mssql-connector';
import { database } from '../../config/database';
import sql from 'mssql';

//export class SP_CALCULARMONTOTOTALCOMPRASPORFECHA {
   // readonly _repository: Datasource;

    //constructor(repository: Datasource) {
    //    this._repository = repository;
    //}

 export const execute = async(params: Params): Promise<sql.IProcedureResult<Result>> => {
       
    // const procedure = new Procedure<Result>('SP_CALCULARMONTOTOTALCOMPRASPORFECHA');
    var request = new sql.Request(database);
        if (params.FechaDesde != null) {
            request.input('FechaDesde', sql.DateTime(), params.FechaDesde);
            // procedure.addParameter('FechaDesde', params.FechaDesde, SqlTypes.DateTime());
        }
        if (params.FechaHasta != null) {
            request.input('FechaHasta', sql.DateTime(), params.FechaHasta);
            // procedure.addParameter('FechaHasta', params.FechaHasta, SqlTypes.DateTime());
        }
    //request.output('output_parameter', sql.VarChar(50));
    const recordsets = await request.execute<Result>('SP_CALCULARMONTOTOTALCOMPRASPORFECHA');
    console.log("RecordSet SP_CALCULARMONTOTOTALCOMPRASPORFECHA",recordsets)
    return recordsets
    //return await this._repository.execProcedure(procedure);

    }
//}

/*
 * All attributes below are optional because MSSQL does not give us the correct information.
 * We'd need to write a custom T-SQL parser to get this piece of information.
 */
export type Params = {
    FechaDesde?: Date; /* datetime */
    FechaHasta?: Date; /* datetime */
};

export type Result = {
    /* Failed to inspect the results of SP_CALCULARMONTOTOTALCOMPRASPORFECHA: CONFLICTING_RESULTS */
    _FailedToInspectTheResults: never; /* This helps making the `Result` type incompatible with others! */
};
