/*
 * This code was auto-generated by generator-mssql-types.
 * See https://github.com/jweyrich/generator-mssql-types for more information.
 * WARNING: If you change anything in this file it may be automatically overwriten!
 */

//import { Datasource, IProcedureResult, Procedure, SqlTypes } from '@internal/mssql-connector';
import { database } from '../../config/database';
import sql from 'mssql';

//export class SP_LISTARUSUARIOS {
   // readonly _repository: Datasource;

    //constructor(repository: Datasource) {
    //    this._repository = repository;
    //}

 export const execute = async(): Promise<sql.IProcedureResult<Result>> => {
       
    // const procedure = new Procedure<Result>('SP_LISTARUSUARIOS');
    var request = new sql.Request(database);
    //request.output('output_parameter', sql.VarChar(50));
    const recordsets = await request.execute<Result>('SP_LISTARUSUARIOS');
    console.log("RecordSet SP_LISTARUSUARIOS",recordsets)
    return recordsets
    //return await this._repository.execProcedure(procedure);

    }
//}


export type Result = {
    IdUsuario: number; /* int */
    DNI?: string; /* varchar(50) */
    Nombre?: string; /* varchar(50) */
    Apellido?: string; /* varchar(50) */
    Email?: string; /* varchar(50) */
    Clave?: string; /* varchar(50) */
    Direccion?: string; /* varchar(50) */
    FechaNacimiento: Date; /* date */
    Telefono?: string; /* varchar(50) */
    Estado?: boolean; /* bit */
    IdRol: number; /* int */
    Descripcion?: string; /* varchar(50) */
} | null;
