/*
 * This code was auto-generated by generator-mssql-types.
 * See https://github.com/jweyrich/generator-mssql-types for more information.
 * WARNING: If you change anything in this file it may be automatically overwriten!
 */

//import { Datasource, IProcedureResult, Procedure, SqlTypes } from '@internal/mssql-connector';
import { database } from '../../config/database';
import sql from 'mssql';

//export class SP_OBTENERPRODUCTOSMASVENDIDOS {
   // readonly _repository: Datasource;

    //constructor(repository: Datasource) {
    //    this._repository = repository;
    //}

 export const execute = async(params: Params): Promise<sql.IProcedureResult<Result>> => {
       
    // const procedure = new Procedure<Result>('SP_OBTENERPRODUCTOSMASVENDIDOS');
    var request = new sql.Request(database);
        if (params.TopN != null) {
            request.input('TopN', sql.Int(), params.TopN);
            // procedure.addParameter('TopN', params.TopN, SqlTypes.Int());
        }
        if (params.FechaDesde != null) {
            request.input('FechaDesde', sql.DateTime(), params.FechaDesde);
            // procedure.addParameter('FechaDesde', params.FechaDesde, SqlTypes.DateTime());
        }
        if (params.FechaHasta != null) {
            request.input('FechaHasta', sql.DateTime(), params.FechaHasta);
            // procedure.addParameter('FechaHasta', params.FechaHasta, SqlTypes.DateTime());
        }
    //request.output('output_parameter', sql.VarChar(50));
    const recordsets = await request.execute<Result>('SP_OBTENERPRODUCTOSMASVENDIDOS');
    console.log("RecordSet SP_OBTENERPRODUCTOSMASVENDIDOS",recordsets)
    return recordsets
    //return await this._repository.execProcedure(procedure);

    }
//}

/*
 * All attributes below are optional because MSSQL does not give us the correct information.
 * We'd need to write a custom T-SQL parser to get this piece of information.
 */
export type Params = {
    TopN?: number; /* int */
    FechaDesde?: Date; /* datetime */
    FechaHasta?: Date; /* datetime */
};

export type Result = {
    IdProducto: number; /* int */
    IdCategoria?: number; /* int */
    Nombre?: string; /* varchar(50) */
    Descripcion?: string; /* varchar(50) */
    Stock: number; /* int */
    PrecioCompra?: number; /* decimal(10, 2) */
    PrecioVenta?: number; /* decimal(10, 2) */
    Estado?: boolean; /* bit */
    FechaRegistro?: Date; /* datetime */
    CategoriaDescripcion?: string; /* varchar(50) */
    codigoProducto?: string; /* varchar(50) */
} | null;
