/*
 * This code was auto-generated by generator-mssql-types.
 * See https://github.com/jweyrich/generator-mssql-types for more information.
 * WARNING: If you change anything in this file it may be automatically overwriten!
 */

//import { Datasource, IProcedureResult, Procedure, SqlTypes } from '@internal/mssql-connector';
import { database } from '../../config/database';
import sql from 'mssql';

//export class SP_OBTENERCATEGORIAPORID {
   // readonly _repository: Datasource;

    //constructor(repository: Datasource) {
    //    this._repository = repository;
    //}

 export const execute = async(params: Params): Promise<sql.IProcedureResult<Result>> => {
       
    // const procedure = new Procedure<Result>('SP_OBTENERCATEGORIAPORID');
    var request = new sql.Request(database);
        if (params.IdCategoria != null) {
            request.input('IdCategoria', sql.Int(), params.IdCategoria);
            // procedure.addParameter('IdCategoria', params.IdCategoria, SqlTypes.Int());
        }
    request.output('Descripcion', sql.NVarChar(100));
    request.output('Estado', sql.Bit());
    //request.output('output_parameter', sql.VarChar(50));
    const recordsets = await request.execute<Result>('SP_OBTENERCATEGORIAPORID');
    console.log("RecordSet SP_OBTENERCATEGORIAPORID",recordsets)
    return recordsets
    //return await this._repository.execProcedure(procedure);

    }
//}

/*
 * All attributes below are optional because MSSQL does not give us the correct information.
 * We'd need to write a custom T-SQL parser to get this piece of information.
 */
export type Params = {
    IdCategoria?: number; /* int */
    Descripcion?: string; /* nvarchar(100) */
    Estado?: boolean; /* bit */
};

export type Result = void;
