/*
 * This code was auto-generated by generator-mssql-types.
 * See https://github.com/jweyrich/generator-mssql-types for more information.
 * WARNING: If you change anything in this file it may be automatically overwriten!
 */

//import { Datasource, IProcedureResult, Procedure, SqlTypes } from '@internal/mssql-connector';
import { database } from '../../config/database';
import sql from 'mssql';

//export class SP_OBTENERPRODUCTOPORCODIGOPRODUCTO {
   // readonly _repository: Datasource;

    //constructor(repository: Datasource) {
    //    this._repository = repository;
    //}

 export const execute = async(params: Params): Promise<sql.IProcedureResult<Result>> => {
       
    // const procedure = new Procedure<Result>('SP_OBTENERPRODUCTOPORCODIGOPRODUCTO');
    var request = new sql.Request(database);
        if (params.CodigoProducto != null) {
            request.input('CodigoProducto', sql.NVarChar(50), params.CodigoProducto);
            // procedure.addParameter('CodigoProducto', params.CodigoProducto, SqlTypes.NVarChar(50));
        }
    //request.output('output_parameter', sql.VarChar(50));
    const recordsets = await request.execute<Result>('SP_OBTENERPRODUCTOPORCODIGOPRODUCTO');
    console.log("RecordSet SP_OBTENERPRODUCTOPORCODIGOPRODUCTO",recordsets)
    return recordsets
    //return await this._repository.execProcedure(procedure);

    }
//}

/*
 * All attributes below are optional because MSSQL does not give us the correct information.
 * We'd need to write a custom T-SQL parser to get this piece of information.
 */
export type Params = {
    CodigoProducto?: string; /* nvarchar(50) */
};

export type Result = {
    IdProducto: number; /* int */
    IdCategoria?: number; /* int */
    Nombre?: string; /* varchar(50) */
    Descripcion?: string; /* varchar(50) */
    Stock: number; /* int */
    PrecioCompra?: number; /* decimal(10, 2) */
    PrecioVenta?: number; /* decimal(10, 2) */
    Estado?: boolean; /* bit */
    FechaRegistro?: Date; /* datetime */
    CategoriaDescripcion?: string; /* varchar(50) */
    codigoProducto?: string; /* varchar(50) */
} | null;
