/*
 * This code was auto-generated by generator-mssql-types.
 * See https://github.com/jweyrich/generator-mssql-types for more information.
 * WARNING: If you change anything in this file it may be automatically overwriten!
 */

//import { Datasource, IProcedureResult, Procedure, SqlTypes } from '@internal/mssql-connector';
import { database } from '../../config/database';
import sql from 'mssql';

//export class SP_OBTENERUSUARIOPORNOMBRE {
   // readonly _repository: Datasource;

    //constructor(repository: Datasource) {
    //    this._repository = repository;
    //}

 export const execute = async(params: Params): Promise<sql.IProcedureResult<Result>> => {
       
    // const procedure = new Procedure<Result>('SP_OBTENERUSUARIOPORNOMBRE');
    var request = new sql.Request(database);
        if (params.Nombre != null) {
            request.input('Nombre', sql.NVarChar(100), params.Nombre);
            // procedure.addParameter('Nombre', params.Nombre, SqlTypes.NVarChar(100));
        }
    //request.output('output_parameter', sql.VarChar(50));
    const recordsets = await request.execute<Result>('SP_OBTENERUSUARIOPORNOMBRE');
    console.log("RecordSet SP_OBTENERUSUARIOPORNOMBRE",recordsets)
    return recordsets
    //return await this._repository.execProcedure(procedure);

    }
//}

/*
 * All attributes below are optional because MSSQL does not give us the correct information.
 * We'd need to write a custom T-SQL parser to get this piece of information.
 */
export type Params = {
    Nombre?: string; /* nvarchar(100) */
};

export type Result = {
    IdUsuario: number; /* int */
} | null;
