/*
 * This code was auto-generated by generator-mssql-types.
 * See https://github.com/jweyrich/generator-mssql-types for more information.
 * WARNING: If you change anything in this file it may be automatically overwriten!
 */

//import { Datasource, IProcedureResult, Procedure, SqlTypes } from '@internal/mssql-connector';
import { database } from '../../config/database';
import sql from 'mssql';

//export class SP_OBTENERULTIMOIDCOMPRA {
   // readonly _repository: Datasource;

    //constructor(repository: Datasource) {
    //    this._repository = repository;
    //}

 export const execute = async(): Promise<sql.IProcedureResult<Result>> => {
       
    // const procedure = new Procedure<Result>('SP_OBTENERULTIMOIDCOMPRA');
    var request = new sql.Request(database);
    //request.output('output_parameter', sql.VarChar(50));
    const recordsets = await request.execute<Result>('SP_OBTENERULTIMOIDCOMPRA');
    console.log("RecordSet SP_OBTENERULTIMOIDCOMPRA",recordsets)
    return recordsets
    //return await this._repository.execProcedure(procedure);

    }
//}


export type Result = {
    IdCompra: number; /* int */
} | null;
