/*
 * This code was auto-generated by generator-mssql-types.
 * See https://github.com/jweyrich/generator-mssql-types for more information.
 * WARNING: If you change anything in this file it may be automatically overwriten!
 */

export { execute as SP_REGISTRARUSUARIO } from './impl/SP_REGISTRARUSUARIO';
export { execute as SP_OBTENERUSUARIOPORNOMBRE } from './impl/SP_OBTENERUSUARIOPORNOMBRE';
export { execute as SP_OBTENERULTIMOIDCOMPRA } from './impl/SP_OBTENERULTIMOIDCOMPRA';
export { execute as SP_OBTENERIDCLIENTEPORDNI } from './impl/SP_OBTENERIDCLIENTEPORDNI';
export { execute as SP_OBTENERDETALLESCOMPRA } from './impl/SP_OBTENERDETALLESCOMPRA';
export { execute as SP_OBTENERCOMPRAS } from './impl/SP_OBTENERCOMPRAS';
export { execute as SP_OBTENERCLIENTES } from './impl/SP_OBTENERCLIENTES';
export { execute as SP_OBTENERCATEGORIASMASVENDIDAS } from './impl/SP_OBTENERCATEGORIASMASVENDIDAS';
export { execute as SP_OBTENERCATEGORIAS } from './impl/SP_OBTENERCATEGORIAS';
export { execute as SP_OBTENERCATEGORIAPORID } from './impl/SP_OBTENERCATEGORIAPORID';
export { execute as SP_LISTARUSUARIOS } from './impl/SP_LISTARUSUARIOS';
export { execute as SP_EDITARUSUARIO } from './impl/SP_EDITARUSUARIO';
export { execute as SP_EDITARCATEGORIA } from './impl/SP_EDITARCATEGORIA';
export { execute as SP_CALCULARMONTOTOTALCOMPRASPORFECHA } from './impl/SP_CALCULARMONTOTOTALCOMPRASPORFECHA';
export { execute as SP_BUSCARCLIENTEPORDNI } from './impl/SP_BUSCARCLIENTEPORDNI';
export { execute as SP_AGREGARDETALLECOMPRA } from './impl/SP_AGREGARDETALLECOMPRA';
export { execute as SP_AGREGARCOMPRA } from './impl/SP_AGREGARCOMPRA';
export { execute as SP_AGREGARCLIENTE } from './impl/SP_AGREGARCLIENTE';
export { execute as SP_AGREGARCATEGORIA } from './impl/SP_AGREGARCATEGORIA';
