POST http://localhost:3033/auth/login
Content-Type: application/json

{
    "DNI": "12345",
    "Clave": "12345"
}

###
GET http://localhost:3033/

###
GET http://localhost:3033/productos

###
GET http://localhost:3033/clientes

###
GET http://localhost:3033/ventas HTTP/1.1

###
GET http://localhost:3033/permisos?idusuario=1


###
GET http://localhost:3033/detallescompra?idCompra=1

###
curl -X POST https://posmatebackend.matiasb.net/productos -H "Content-Type: application/json" -d '{
    "oCategoria": {
        "IdCategoria": 1
    },
    "Nombre": "Nuevo Producto11",
    "Descripcion": "Descripción del nuevo producto",
    "Stock": 100,
    "PrecioCompra": 50.00,
    "PrecioVenta": 60.00,
    "Estado": "Activo",
    "FechaRegistro": "2023-11-14T16:17:16.607",
    "codigoProducto": "NP125"
}'

###
curl -X PUT http://localhost:3033/productos/1 -H "Content-Type: application/json" -d '{
    "oCategoria": {
        "IdCategoria": 1
    },
    "Nombre": "Producto Editado",
    "Descripcion": "Descripción del producto editado",
    "Stock": 150,
    "PrecioCompra": 55.00,
    "PrecioVenta": 65.00,
    "Estado": "Activo",
    "FechaRegistro": "2023-11-14T16:17:16.607",
    "codigoProducto": "NP12345"
}'

###
GET  https://posmatebackend.matiasb.net/productos/codigo/P001 HTTP/1.1
###
GET  http://localhost:3033/productos/codigo/P001 HTTP/1.1

###
GET https://posmatebackend.matiasb.net/productos/1 HTTP/1.1


###
curl -X PUT http://localhost:3033/productos/1/actualizarStock -H "Content-Type: application/json" -d '{"cantidad": 10}'

###
curl -X PUT http://localhost:3033/productos/1/actualizarStockVenta -H "Content-Type: application/json" -d '{"cantidad": 5}'

###
curl -X GET "http://localhost:3033/productos/masvendidos?topN=5&fechaDesde=2023-01-01&fechaHasta=2023-12-31" -H "Content-Type: application/json"

###
curl -X POST http://localhost:3033/compras -H "Content-Type: application/json" -d '{
    "oUsuario": { "IdUsuario": 1 },
    "oProveedor": { "IdProveedor": 2 },
    "MontoTotal": 150.00,
    "FechaRegistro": "2023-11-14T16:17:16.607"
}'

###
curl -X POST http://localhost:3033/ventas -H "Content-Type: application/json" -d '{
    "oUsuario": { "IdUsuario": 1 },
    "oCliente": { "IdCliente": 2 },
    "MontoPago": 200.00,
    "MontoCambio": 50.00,
    "MontoTotal": 150.00,
    "FechaRegistro": "2023-11-14T16:17:16.607"
}'

###
curl -X GET "http://localhost:3033/ventas/ultimoid"
###
curl -X GET "http://localhost:3033/compras/ultimoid"

###
curl -X POST "http://localhost:3033/detallecompra" -H "Content-Type: application/json" -d '{
    "IdCompra": 1,
    "oProducto": {
        "IdProducto": 1
    },
    "PrecioCompra": 10.00,
    "PrecioVenta": 15.00,
    "Cantidad": 5,
    "MontoTotal": 50.00,
    "FechaRegistro": "2023-01-01T00:00:00"
}'

###
curl -X GET "http://localhost:3033/detallesventa?idVenta=1"
###
curl -X POST "http://localhost:3033/detalleventa" -H "Content-Type: application/json" -d '{
    "IdVenta": 1,
    "oProducto": {
        "IdProducto": 1
    },
    "PrecioVenta": 15.00,
    "Cantidad": 2,
    "Subtotal": 30.00,
    "FechaRegistro": "2023-01-01T00:00:00"
}'



