POST http://localhost:3033/auth/login
Content-Type: application/json

{
    "DNI": "12345",
    "Clave": "12345"
}

###
GET http://localhost:3033/

###
GET http://localhost:3033/productos

###
GET http://localhost:3033/clientes

###
GET http://localhost:3033/permisos?idusuario=1

