version: '3.9'

networks:
  posmate-backend-network:
    driver: bridge

services:
  posmate-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    container_name: posmate-sqlserver
    networks:
      - posmate-backend-network
    restart: always
    env_file:
      - sqlserver.env
      - sapassword.env
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $$MSSQL_SA_PASSWORD -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    ports:
      #- '1433:1433'
      # Si el puerto 1433 esta ocupado en el host, usar el puerto 1533
      - '1433:1433'
    volumes: 
      - ./data/mssql:/var/opt/mssql
      - ./data/sqlserver:/var/opt/sqlserver
      - ./data/usr/shared:/usr/shared
  posmate-api: 
    build: ../backend
    container_name: posmate-api
    restart: unless-stopped
    env_file:
      - backend.env 
    ports:
      - '3000:3000'
    deploy:
      replicas: 1
    depends_on: 
      posmate-sqlserver:
        condition: service_healthy
    networks:
      - posmate-backend-network